### ISSUE TITLE
Phtml example error

### ISSUE THREAD

**Issue by thekotekjournal** [jomaingilbert/jsostream#9]
# Error

Please fix phtml owner I can not use the tab after compile. It must be very untidy and must be difficult to find if there is an error after compile.

**Comment by jonathanmarp** [comment]
# Thank you for giving me the issue

Ok my first. Will try to solve the problem.
Secondly you can try online the use of this example code
Thirdly you can take code cdn. Retrieving jsostream library and phtml's cdn. If you do not install jsostream you will experience an error. Because the script requires jsostream library. 

The link: https://defensegame.rf.gd/phtml/

**Comment by jonathanmarp** [comment]
# CDN

https://defensegame.rf.gd/phtml/jsostream.js
https://defensegame.rf.gd/phtml/phtml.js

<script src="https://defensegame.rf.gd/phtml/jsostream.js"></script>
<script src="https://defensegame.rf.gd/phtml/phtml.js"></script>

Use
You create a script that contains functions
That function is phtml(string): string

So I have variable a = phtml("@main");
The result <!DOCTYPE html>
